services:
  shopping-list:
    build: .
    container_name: shopping-list
    restart: always
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./static:/app/static
    env_file:
      - .env
